name: Build

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

env:
  SPIN_OPERATOR_RELEASE: v0.2.0

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: 0.123.0
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Hugo CLI
        run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb \
          && sudo dpkg -i ${{ runner.temp }}/hugo.deb

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install Node.js dependencies
        run: npm ci

      - name: Setup Go environment
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'
          cache: true

      - name: Generate CRD reference docs
        run: ./generate.sh
        working-directory: ./crd-reference
        env:
          SPIN_OPERATOR_RELEASE: ${{ env.SPIN_OPERATOR_RELEASE }}

      - name: Build
        run: |
          hugo \
            --gc \
            --minify
